[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["lesguillemets <kgkacko+github@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"
